### ISSUE TITLE
用avataaars组件实现头像

### ISSUE THREAD

**Issue by yezhuoyang** [Team-Salt/Front-React#109]
盐圈帖子，回复，论文看法的头像均采用开源的avataaars组件。
注册时用户可以自定义样式

**Comment by DDDDDDDOU** [comment]
# 组件已被重新封装为AvatarPannel组件

**_TODO：_**：
+ 将ForumCard、PostCard等Card组件中的**头像**进行替换，传入参数请参照AvatarPannel组件注释。使用方法可参照LoginForm组件中的注册部分。
+ 将ForumCard、PostCard等Card组件中的**个人信息**进行填入。

`以上部分数据都在组件中ready，只需要填入即可`

+ 将searchhead组件中的**头像**和**用户信息**部分进行替换，**此部分需要自行请求数据**，用户id和个人信息的本地缓存请参考src/Source/Modal/storage.txt

**Comment by DDDDDDDOU** [comment]
Asign to @Qaplagzy
