### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by yezhuoyang** [Team-Salt/Front-React#61]
<img width="1430" alt="截屏2021-12-08 下午8 14 38" src="https://user-images.githubusercontent.com/34168020/145206915-56ade801-6987-4b87-8393-b637ae8b09d5.png">

当我做标注的时候出现这个错误

**Comment by DDDDDDDOU** [comment]
bug已被修复 @DDDDDDDOU
