### ISSUE TITLE
TypeError:Cannot read read properties of undifined (reading 'poster Avatar')

### ISSUE THREAD

**Issue by yezhuoyang** [Team-Salt/Front-React#67]
- [ ]
<img width="1226" alt="截屏2021-12-22 上午9 39 15" src="https://user-images.githubusercontent.com/34168020/147020528-48409fb7-e1b3-4467-b54b-c9808a3e820a.png">
 
当我在主页上点击"盐圈"的时候，前端直接报错。头像的处理有错误

**Comment by DDDDDDDOU** [comment]
对item做了空安全验证，bug fixed
