### ISSUE TITLE
当数据库中没有Tag的时候，科研图谱页面会报错

### ISSUE THREAD

**Issue by yezhuoyang** [Team-Salt/Front-React#72]
现在我在主页上点击科研图谱，数据库里没有数据，页面不能正常渲染，对无数据的情况要处理一下。

<img width="1152" alt="截屏2021-12-28 上午10 50 28" src="https://user-images.githubusercontent.com/34168020/147522847-0b758b80-b715-4441-afa4-ffacbc170d7f.png">

**Comment by Qaplagzy** [comment]
加个非空判断 
类似于`?? ''`
