### ISSUE TITLE
论文详情页面收藏，引用，进入阅读器按钮

### ISSUE THREAD

**Issue by yezhuoyang** [Team-Salt/Front-React#74]
目前只有点赞接口做好了。

<img width="1318" alt="截屏2021-12-28 下午3 14 40" src="https://user-images.githubusercontent.com/34168020/147539110-28220bfd-dc1f-401a-9d8b-223ec708370e.png">

**Comment by yezhuoyang** [comment]
文献页面里，一张论文卡片当中的这几个接口也没有完成
<img width="1408" alt="截屏2021-12-28 下午3 32 19" src="https://user-images.githubusercontent.com/34168020/147540473-36c2a0a1-4425-4e19-97f8-e729e7622cd6.png">

进入阅读器现在并没有进入相应论文的阅读器
卡片当中应该筛选高赞看法，现在并没有
卡片应该支持用户查看精选论文图片

**Comment by DDDDDDDOU** [comment]
+ 引用需要后端提供接口和生成引用格式
+ 下载需要提供PDF数据
+ 阅读器按钮需要有PDF数据，否则阅读器页面没有论文数据
+ 收藏功能有接口吗 ❓ 
+ 高赞看法没有接口
