### ISSUE TITLE
Tag查看无法跳转至学科详情页面

### ISSUE THREAD

**Issue by yezhuoyang** [Team-Salt/Front-React#78]
如图所示，当我点击“三维图像理解”的查看按钮后
<img width="1105" alt="截屏2021-12-28 下午3 57 33" src="https://user-images.githubusercontent.com/34168020/147542926-317cbc65-02b8-492b-a5b0-15a3d40e67d4.png">
按照设计应该跳转至学科详情页面，有Tag介绍，图片，相关论文
<img width="1488" alt="截屏2021-12-28 下午3 57 51" src="https://user-images.githubusercontent.com/34168020/147542936-5839720f-a112-4753-8dc0-c09088e659df.png">
但是现在跳转的时候报错

**Comment by yezhuoyang** [comment]
Tag详情页面的设计如下:
<img width="666" alt="截屏2021-12-30 上午10 25 36" src="https://user-images.githubusercontent.com/34168020/147716782-448efdf5-a0af-40e8-a466-6872f757780a.png">

**Comment by DDDDDDDOU** [comment]
功能点已被完成 @DDDDDDDOU
