### ISSUE TITLE
盐圈卡片信息未跟后端对接

### ISSUE THREAD

**Issue by yezhuoyang** [Team-Salt/Front-React#82]
如下图所示，默认图片展示应该去掉，发帖用户信息未跟后端对接。

<img width="977" alt="截屏2021-12-28 下午4 42 09" src="https://user-images.githubusercontent.com/34168020/147547182-0e236daf-9f05-4b07-b9dc-6ec2b08ad5f7.png">

**Comment by DDDDDDDOU** [comment]
功能点已被完成 @DDDDDDDOU
