### ISSUE TITLE
盐圈单个帖子(forum)详情页面回帖(post)未正确对接

### ISSUE THREAD

**Issue by yezhuoyang** [Team-Salt/Front-React#83]
如下图所示，盐圈回复没有正确展示

<img width="1464" alt="截屏2021-12-28 下午4 53 12" src="https://user-images.githubusercontent.com/34168020/147548187-2029ea8c-b359-4518-8fdc-76921b3d04a8.png">

**Comment by DDDDDDDOU** [comment]
功能点已被完成 @DDDDDDDOU
