### ISSUE TITLE
盐圈发帖页面(WangEditor)

### ISSUE THREAD

**Issue by yezhuoyang** [Team-Salt/Front-React#91]
用WangEditor允许与设计略有出入，跟后端对接，支持修改帖子

<img width="884" alt="截屏2021-12-30 上午10 36 17" src="https://user-images.githubusercontent.com/34168020/147717210-0c19ed77-0c14-4da7-a06d-ba74fa45b45f.png">

**Comment by DDDDDDDOU** [comment]
功能点已被完成 @DDDDDDDOU
